name: DevOps CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Application Dependencies
      run: npm install

    - name: Build Docker Container Image
      run: docker build -t ecommerce-inventory:latest .